### ISSUE TITLE
Issue with Model

### ISSUE THREAD

**Issue by aotgamerz** [webrium/foxql#10]
Is there a other way of inherting the `Model` class?

the issue is i can't extend 2 classes at once.
for example `Player` class extends `Human`. so how i can make Player a Model?

**Comment by benkhalife** [comment]
I think you should extend the `Model` in `Human` and then extend the `Human` in `Player`

**Comment by PixyBoi69** [comment]
`Human` extends `Entity` and i can't edit the library

**Comment by benkhalife** [comment]
Now the 'ModelTrait' class can be used instead of 'Model' without 'extends'

```PHP
<?php
namespace App\Models;

use Foxdb\ModelTrait;

class User{

  use ModelTrait;
  

  /**
  * The table associated with the model.
  *
  * @var string
  */
  protected $table = 'users';

}
```
